plugins {
    id 'java'
}

group 'io.github.sodalisretro'
version '1.0-SNAPSHOT'

dependencies {
    implementation files('microemulator-2.0.4/microemulator.jar')
}

jar {
    manifest {
        attributes(
                'MIDlet-Vendor': MIDletVendor,
                'MIDlet-Version': MIDletVersion,
                'MicroEdition-Configuration': MicroEditionConfiguration,
                'MIDlet-Name': MIDletName,
                'MIDlet-Description': MIDletDescription,
                'MicroEdition-Profile': MicroEditionProfile,
                'MIDlet-1': MIDletName + ',' + icon + ',' + mainClass
        )
    }
}

tasks.register('generateJad') {
    dependsOn jar
    doLast {
        def jarFile = jar.getArchiveFile().get().asFile
        def jadFile = new File(jarFile.parentFile, jarFile.name.replace('.jar', '.jad'))

        def jadProperties = [
                'MIDlet-Name'                : MIDletName,
                'MIDlet-Version'             : MIDletVersion,
                'MIDlet-Vendor'              : MIDletVendor,
                'MIDlet-1'                   : "${MIDletName}, ${icon}, ${mainClass}",
                'MicroEdition-Configuration' : MicroEditionConfiguration,
                'MicroEdition-Profile'       : MicroEditionProfile,
                'MIDlet-Description'         : MIDletDescription,
                'MIDlet-Jar-URL'             : jarFile.name,
                'MIDlet-Jar-Size'            : jarFile.length()
        ]

        jadFile.text = jadProperties.collect { key, value -> "${key}: ${value}" }.join('\n') + '\n'
    }
}

tasks.register('runEmulator') {
    dependsOn jar
    doLast {
        javaexec {
            mainClass = 'org.microemu.app.Main'
            classpath = files("./microemulator-2.0.4/microemulator.jar")
            args = [
                    jar.getArchiveFile().get().asFile.getAbsolutePath()
            ]
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_2
    targetCompatibility = JavaVersion.VERSION_1_1
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// Auto-generate .jad after jar built
build.dependsOn generateJad
